# Generated by Django 4.2.2 on 2023-06-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.licensecategory'),
        ),
    ]
