# Generated by Django 4.2.2 on 2023-07-27 10:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_license_address_alter_license_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
